#!/usr/bin/env dash

# Variable explain:
# $y: the current argument in the whole content
# $yy: the current argument in the list
# $pos: the current position on argument y
# $y2: the current position on current screen position (invert color using SGR 33 7)
# $num: numbers of lines per argument
# $fin: bottom for printable area, depends on num
# $token: indicator for actions
# Dimension is adjustable by $top & $bottom

# Stolen from shfm
# Reference for color: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences
# Reference for vt100: https://vt100.net/docs/vt510-rm/contents.html
# Reference for escape sequence: https://github.com/dylanaraps/pure-sh-bible#escape-sequences
esc() {
    case $1 in
        # vt100 (IL is vt102) (DECTCEM is vt520)
	CUP)     printf '%s[%s;%sH' "$esc_c" "$2" "$3" ;; # cursor to LINES($2), COLUMNS($3)
        CUU)     printf '%s[%sA'    "$esc_c" "$2"      ;; # cursor up
        CUD)     printf '%s[%sB'    "$esc_c" "$2"      ;; # cursor down
        CUR)     printf '%s[%sC'    "$esc_c" "$2"      ;; # cursor right
	CUL)     printf '%s[%sD'    "$esc_c" "$2"      ;; # cursor left
	DECAWM)  printf '%s[?7%s'   "$esc_c" "$2"      ;; # (h: set; l: unset) line wrap
        DECRC)   printf '%s8'       "$esc_c"           ;; # cursor restore
        DECSC)   printf '%s7'       "$esc_c"           ;; # cursor save
        DECSTBM) printf '%s[%s;%sr' "$esc_c" "$2" "$3" ;; # scroll region
        DECSLRM) printf '%s[%s;%ss' "$esc_c" "$2" "$3" ;; # Set left and right margin
	DECTCEM) printf '%s[?25%s'  "$esc_c" "$2"      ;; # (h: show; l: hide) cursor visible
	ED[0-2]) printf '%s[%sJ'    "$esc_c" "${1#ED}" ;; # clear screen
        EL[0-2]) printf '%s[%sK'    "$esc_c" "${1#EL}" ;; # clear line
        IL)      printf '%s[%sL'    "$esc_c" "$2"      ;; # insert line
	SGR)     printf '%s[%s;%sm' "$esc_c" "$2" "$3" ;; # colors ($2); attribute ($3)

        # xterm (since 1988, supported widely)
	screen_alt) printf '%s[?1049%s' "$esc_c" "$2" ;; # (h: to; l: back from) alternate buffer
    esac
}

term_setup() {
    bottom=$((LINES - 2))				# space for bottom status_line
    top=3						# space for top status_line
    fin=$(( bottom - (bottom - (top - 1)) % num ))	# bottom for content printed

    stty=$(stty -g)
    stty -icanon -echo
    esc screen_alt h
    esc DECAWM l
    esc DECTCEM l
    esc ED2
    esc DECSTBM "$top" "$fin"
}

term_getsize() {
    # false-positive, behavior intentional, globbing is disabled.
    # shellcheck disable=2046
    {
        set -f -- $(stty size)
        set +f
    }

    LINES=$1 COLUMNS=$2
}

term_reset() {
    esc DECAWM h     >&2
    esc DECTCEM h    >&2
    esc ED2          >&2
    esc DECSTBM      >&2
    esc DECSLRM      >&2
    esc screen_alt l >&2
    stty "$stty"
}

old_save() { old_num=$num old_y=$y old_yy=$yy old_y2=$y2 old_pos=$pos old_cur=$cur old_format=$format old_msg=$msg old_ltype=$ltype old_last=$last old_len=$len; }

old_reset() { num=$old_num y=$old_y yy=$old_yy y2=$old_y2 pos=$old_pos cur=$old_cur format=$old_format msg=$old_msg ltype=$old_ltype last=$old_last len=$old_len; }

cur_assign() { shift "$1"; cur=$1; } # assign $cur > 9

input_assign() {
    local offset=$1
    local length=$2
    local save_list
    shift "$offset"; shift 2;
    for i in $(seq $length); do
	save_list="$save_list${ifs:=$nl}$1"
	shift $(( $# > 0 ? 1 : 0 ))
    done
    save_list="${save_list#${ifs:=$nl}}"
    list=$save_list
}


redraw() {
    local list

    pos=$(( num * y - num + top ))
    end=$(( fin + 1 ))
    mid=$(( end / 4 < 5 ? 1 : end / 4 ))
    width=$(( (end - top) / num ))

    case $hist in
        2) # redraw after cmd run
	    shift "$((pos >= y2 ? (pos - y2) / num : 0))"
        ;;

        1) # redraw after go back
	    input_assign "$((pos >= fin ? (pos - y2) / num : 0))" "$width" "$@"
	    unset hist
        ;;

        *) # everything else
	    input_assign "$(( y >= width ? y - width : 0 ))" "$width" "$@"
        ;;
    esac

    IFS=${ifs:=$nl}
    set -- $list
    unset IFS

    esc ED2

    status_line "$last"
    list_print "$@"
}


list_print() {
    esc CUP "$top"

    i=1

    for file do

	case $(( num * i - num + top - end )) in
	    -*)
		list_format "$file"
		esc CUD
		i=$((i + 1))
		;;
	esac

    done

    esc CUP "$(( pos > y2 ? y2 : pos ))"
}

list_format() {
    esc EL0

    # overall display rule
    case $(( num * i - num + top )) in
	"$y2") esc CUR 2; esc SGR 35 1; printf '>'; esc SGR 33 1; esc CUR 2 ;;
	*)
	    esc CUR 5
	    esc SGR '' 2
	    ;;
    esac

    # content display format
    case "$format" in
	basename) printf '%s\r' "${1##*/}" ;;
	nldel) printf '%s\r' "${1%$nl}" ;;
	'') printf '%s\r' "$1" ;;
    esac

    esc SGR
}

arg_print() {
    offset=$1
    shift "$offset"
    arg_format "$1"
}


arg_format() {
    esc EL0

    # overall display rule
    case "$cur" in
	'') esc CUR 5; esc SGR '' 2 ;;
	*) esc CUR 2; esc SGR 35 1; printf '>'; esc SGR 33 1; esc CUR 2 ;;
    esac

    # content display format
    case "$format" in
	basename) printf '%s\r' "${1##*/}" ;;
	nldel) printf '%s\r' "${1%$nl}" ;;
	'') printf '%s\r' "$1" ;;
    esac

    esc SGR
}


term_move_up() {

    y=$(( y - move )) yy=$(( yy - move ))
    pos=$(( num * y - num + top ))

    # Generate list for partial input
    input_assign "$((yy - 1))" "$((move + 1))" "$@"
    IFS=${ifs:=$nl}
    set -- $list
    unset IFS list cur

    for i in $(seq 1 $move); do
	arg_print "$((move - i + 2))" "$@" # print the latter item first

	case "$y2" in # adjust for upper bound
	    $top) [ $num -gt 1 ] && esc CUU $((num - 1)); esc IL "$num" ;;
	    *) esc CUU "$((num * 2 - 1))"; y2=$(( y2 > top ? y2 - num : top )) ;;
	esac
    done
    offset=$y
    cur=$1
    arg_format "$1"

    # Restore cursor to match y2
    [ $num -gt 1 ] && esc CUU "$((num - 1))"

    status_line "$last"
}

term_move_down() {

    y=$(( y + move )) yy=$(( yy + move ))
    pos=$(( num * y - num + top ))
    y2=$(( y2 + num * move < fin - (num - 1) ? y2 + num * move : fin - (num - 1) ))

    # Generate list for partial input
    input_assign "$((yy - move - 1))" "$((move + 1))" "$@"
    IFS=${ifs:=$nl}
    set -- $list
    unset IFS cur

    for i in $(seq 1 $move); do
	arg_format "$1"
	shift 1
	printf '\n'
    done
    offset=$y
    cur=$1
    arg_format "$1"

    [ $num -gt 1 ] && esc CUU "$((num - 1))"

    status_line "$last"
}

status_line () {
    esc DECSC
    esc CUP 1
    esc EL2; printf '%s %s' "($y/$1)" "$msg"
    [ -n "$ltype" ] && { esc CUP "$LINES"; esc EL2; printf '%s' "$ltype"; }
    esc DECRC
}

prompt() {
    esc DECSC
    esc CUP "$LINES"
    printf %s "$1"
    esc DECTCEM h
    esc EL0

    case $2 in
        r)
	    stty -cread icanon echo 1>/dev/null 2>&1
	    read -r ans ||:
	    stty -icanon -echo
	    ;;
    esac

    esc DECRC
    esc DECTCEM l
}

search() {
    local content="$1"
    local IFS="$2"
    local str="$3"
    local filter posnum lower_content lower_str i j n

    case $case_insense in
	1) # case-insensitive filter
	    # lowercase both content and str
	    lower_content=$(printf '%s' "$content" | tr '[:upper:]' '[:lower:]')
	    lower_str=$(printf '%s' "$str" | tr '[:upper:]' '[:lower:]')

	    # First run: match lowercase and record the number of positional parameter
	    i=1
	    set -- $lower_content
	    for line do
		case $line in
		    *$lower_str*) posnum="$posnum $i" ;;
		esac
		i=$((i+1))
	    done
	    posnum=${posnum#* } # delete first space

	    # Second run: match the item based on that list above
	    set -- $content

	    j=1
	    for line do
		n=${posnum%% *} # first line number
		case $j in
		    "$n")
			filter="$filter$IFS$line"
			posnum=${posnum#* } # delete first numer
			;;
		esac
		j=$((j+1))
	    done

	    ;;
	*) # case-sensitive filter
	    set -- $content
	    for line do
		case $line in
		    *$str*) filter="$filter$IFS$line" ;;
		esac
	    done
	    ;;
    esac

    filt_out=${filter#*$IFS}
}

usage () {
cat << 	EOF
Usage:

shellect [OPTIONS] ([ARGS])

  -h,			Show help options
  -i,			Set case-insensitive search
  -n=[num],		Set numbers of line per entry
  -d=[delim],		Set delimiter (IFS, internal field separator)
  -c=[content],		Set content to display
  -f=[format],		Set the format to print out content
  -t=[msg],		Set top status bar message
  -b=[msg],		Set bottom status bar message

format detail:
  nldel			delete last nl, equiv to "\${1%\$nl}"
  basename		only print basename, equiv to "\${1##*/}" ;;

  if unset or empty, then equiv to "\$1"

EOF
}

key() {

    # Generate new list
    case $((y - move)) in
        1) y=1; yy=1; input_assign "0" "$len" "$@" ;;
	$((last - move - 1))) y=$last; input_assign "$((y - $len))" "$len" "$@" ;;
	*)
	    case $((y - $len)) in
	        -*) input_assign "$((yy > 1 ? y - yy : y - 1))" "$len" "$@" ;;
		*) input_assign "$((yy > 1 ? y - len : y - 1))" "$len" "$@" ;;
	    esac
    esac

    IFS=${ifs:=$nl}
    set -- $list
    unset IFS

    while key=$(dd ibs=1 count=1 2>/dev/null); do

	case $key${esc:=0} in
	    "$ctrl_u"?|~5)
		move=$(((end - top) / (4 * num) > 2 ? (end - top) / (4 * num) : 2))

		# Terminal condition
		case $y in
		    -*|0|1) continue ;;
		esac

		# Adjust move step
		case $((y - move - 1)) in
		    -*|0) move=$((y - 1)) ;;
		esac

		# Move or update list
		case $(( yy - move )) in
		    -*|0) yy=$(( y > len ? len : y )); return 0 ;;
		    *) term_move_up "$@" ;;
		esac
	    ;;

	    "$ctrl_f"?|~6)
		move=$(((end - top) / (4 * num) > 2 ? (end - top) / (4 * num) : 2))

		# Terminal condition
		case $y in
		    $last) continue ;;
		esac

		# Adjust move step
		case $(( y - $last + move )) in
		    [1-9]*) move=$(($last - y)) ;;
		esac

		# Move or update list
		case $(( yy - $len + move )) in
		    -*|0) term_move_down "$@" ;;
		    *) yy=1; return 0 ;;
		esac
	    ;;

	    k?|A2|"$ctrl_p"?)
		move=1

		# Terminal condition
		case $y in
		    -*|0|1) continue ;;
		esac

		# Move or update list
		case $(( yy - move )) in
		    -*|0) yy=$len; return 0 ;;
		    *) term_move_up "$@" ;;
		esac
	    ;;

	    j?|B2|"$ctrl_n"?)
		move=1

		# Terminal condition
		case $y in
		    $last) continue ;;
		esac

		# Move or update list
		case $(( yy - $len + move )) in
		    -*|0) term_move_down "$@" ;;
		    *) yy=1; return 0 ;;
		esac
	    ;;

	    g?|H2|"$ctrl_a"?)
		case $y in
		    1) continue ;;
		esac

		case $token in
		    '/')
			IFS=${ifs:=$nl}
			set -- $filt_out
			unset IFS
			;;
		    '')
			IFS=${ifs:=$nl}
			set -- $content
			unset IFS
		esac

		y=1 yy=1 y2=$top cur=$1
		redraw "$@"
		return 0
	    ;;

	    G?|F2|"$ctrl_e"?)
		case $y in
		    $last) continue ;;
		esac

		case $token in
		    '/')
			IFS=${ifs:=$nl}
			set -- $filt_out
			unset IFS
			;;
		    '')
			IFS=${ifs:=$nl}
			set -- $content
			unset IFS
		esac

		y=$last yy=$len pos=$(( num * y - num + top ))
		y2=$(( pos < fin - (num - 1) ? pos : fin - (num - 1) ))

		cur_assign "$y" "$@"
		redraw "$@"
		return 0
	    ;;

	    l?|C2|"$esc") # ARROW RIGHT
		case $token in
		    '?') ;;
		    *)
			term_reset
			return 1
			;;
		esac
	    ;;

	    h?|D2|"$bs_char"?) # ARROW LEFT

		case $token in
		    '?'|'/')
			unset token
			old_reset
			IFS=${ifs:=$nl}
			set -- $content
			unset IFS
			y=1 yy=1 y2=$top cur=$1
			redraw "$@"
			return 0
			;;
		esac
	    ;;

	    /?)
		prompt / r
		search "$content" "$ifs" "$ans"
		IFS=${ifs:=$nl}
		set -- $filt_out
		unset IFS
		case $# in
		    0)
			num=1
			set -- 'no result'
			;;
		esac

		old_save
		y=1 yy=1 y2=$top cur=$1 last=$# ltype="Search mode" msg="Search by *$ans*" token='/'
		len=$(($# > 500 ? 500 : $#))
		redraw "$@"
		return 0
	    ;;

	    \??)
		set -- 'k/↑/Ctrl-p - up' \
		       'j/↓/Ctrl-n - down' \
		       'l/→ - right' \
		       'h/← - left' \
		       'Ctrl-f/PageDown - PageDown' \
		       'Ctrl-u/PageUp - PageUp' \
		       'g/Home/Ctrl-a - go to top' \
		       'G/End/Ctrl-e - go to bottom' \
		       '/ - search' \
		       '? - show keybinds' \
		       'q - quit'

		old_save
		unset format
		num=1 y=1 yy=1 y2=$top cur=$1 last=$# ltype= msg=keybinds token='?'
		redraw "$@"
	    ;;

	    q?)
		term_reset
		exit 0
		;;
	    "$esc_c"*) esc=1 ;;
		 '[1') esc=2 ;;
		   5?) esc=5 ;; # PageUp
		   6?) esc=6 ;; # PageDown
		    *) esc=0 ;;
	esac
    done
}

main() {

    trap 'term_reset' INT
    trap 'term_getsize; term_setup; y=1 y2=$top; redraw "$@"' WINCH

    term_getsize
    term_setup
    y=1 yy=1 y2=$top cur=$1

    IFS=${ifs:=$nl}
    set -- $content
    unset IFS
    last=$#
    len=$(($# > 500 ? 500 : $#))

    redraw "$@"

    while [ $? -eq 0 ]; do
	case $token in
	    '/')
		IFS=$ifs
		set -- $filt_out
		unset IFS
		;;
	    '')
		IFS=${ifs:=$nl}
		set -- $content
		unset IFS
	esac
	key "$@"
    done
}

nl='
'
tab='	'

# special key setting
esc_c=$(printf '\033')
bs_char=$(printf '\177')
ctrl_f=$(printf '\006')
ctrl_u=$(printf '\025')
ctrl_n=$(printf '\016')
ctrl_p=$(printf '\020')
ctrl_a=$(printf '\001')
ctrl_e=$(printf '\005')
tilda=$(printf '\176')

while getopts "t:b:n:d:s:c:f:hi" result; do
    case "${result}" in
        n) num=${OPTARG} ;;
        d) ifs=${OPTARG} ;;
        c) content=${OPTARG} ;;
        f) format=${OPTARG} ;;
	i) case_insense=1 ;;
	t) msg="${OPTARG}" ;;
	b) ltype="${OPTARG}" ;;
	h) usage && exit 0 ;;
    esac
done

case "$content" in
    '') content=$(cat -u -) ;; # Accept pipe stdin
esac

num=${num:=1} # num=1 if unset
main <&2 >/dev/tty # why it works, I don't know.
printf '%s' "$cur" >&1
