#!/bin/sh

# Stolen from shfm
# Reference: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences
esc() {
    case $1 in
        # vt100 (IL is vt102) (DECTCEM is vt520)
	CUP)     printf '%s[%s;%sH' "$esc_c" "$2" "$3" ;; # cursor to LINES($2), COLUMNS($3)
        CUU)     printf '%s[%sA'    "$esc_c" "$2"      ;; # cursor up
        CUD)     printf '%s[%sB'    "$esc_c" "$2"      ;; # cursor down
        CUR)     printf '%s[%sC'    "$esc_c" "$2"      ;; # cursor right
	CUL)     printf '%s[%sD'    "$esc_c" "$2"      ;; # cursor left
	DECAWM)  printf '%s[?7%s'   "$esc_c" "$2"      ;; # (h: set; l: unset) line wrap
        DECRC)   printf '%s8'       "$esc_c"           ;; # cursor restore
        DECSC)   printf '%s7'       "$esc_c"           ;; # cursor save
        DECSTBM) printf '%s[%s;%sr' "$esc_c" "$2" "$3" ;; # scroll region
	DECTCEM) printf '%s[?25%s'  "$esc_c" "$2"      ;; # (h: show; l: hide) cursor visible
	ED[0-2]) printf '%s[%sJ'    "$esc_c" "${1#ED}" ;; # clear screen
        EL[0-2]) printf '%s[%sK'    "$esc_c" "${1#EL}" ;; # clear line
        IL)      printf '%s[%sL'    "$esc_c" "$2"      ;; # insert line
        SGR)     printf '%s[%s;%sm' "$esc_c" "$2" "$3" ;; # colors

        # xterm (since 1988, supported widely)
	screen_alt) printf '%s[?1049%s' "$esc_c" "$2" ;; # (h: to; l: back from) alternate buffer
    esac
}

term_setup() {
    bottom=$((LINES - 2))				# space for bottom status_line
    top=3		  				# space for top status_line
    fin=$(( bottom - (bottom - (top - 1)) % num ))	# bottom for content printed

    stty=$(stty -g)
    stty -icanon -echo
    esc screen_alt h
    esc DECAWM l
    esc DECTCEM l
    esc ED2
    esc DECSTBM "$top" "$fin"
}

term_resize() {
    # false-positive, behavior intentional, globbing is disabled.
    # shellcheck disable=2046
    {
        set -f -- $(stty size)
        set +f
    }

    LINES=$1 COLUMNS=$2
}

term_reset() {
    esc DECAWM h     >&2
    esc DECTCEM h    >&2
    esc ED2          >&2
    esc DECSTBM      >&2
    esc screen_alt l >&2
    stty "$stty"
}

redraw() {
    esc ED2

    status_line_top
    list_print "$@"
    status_line_bottom "$#"
}


list_print() {
    esc CUP "$top"

    i=1
    pos=$(( num * y - num + top ))
    end=$(( fin + 1 ))
    mid=$(( end / 4 < 5 ? 1 : end / 4 ))

    case $hist in
        2) # redraw after cmd run
	    shift "$((pos >= y2 ? (pos - y2) / num : 0))"
        ;;

        1) # redraw after go back
	    shift "$((pos >= fin ? (pos - y2) / num : 0))"
	    unset hist
        ;;

        *) # everything else
	    shift "$((y >= (end - top) / num ? y - (end - top) / num : 0 ))"
        ;;
    esac

    for file do

	# same formula as $pos
	case $(( num * i - num + top )) in
	    $y2) esc SGR 33 7 ;;
	esac

	case $(( num * i - num + top - end )) in
	    -*)
		arg_format "$file"
		esc CUD
		;;
	esac
	i=$((i + 1))
    done

    esc CUP "$(( pos > y2 ? y2 : pos ))"
}

cur_assign(){ # assign $cur > 9
    shift "$1"
    cur=$1
}

old_reset() {
    num=$old_num y=$old_y y2=$old_y2 pos=$old_pos cur=$old_cur
}

arg_print() {
    local offset=$1

    case $offset in
        "$y") esc SGR 33 7
    esac

    shift "$offset"

    case $offset in
        "$y") cur=$1
    esac

    arg_format "$1"
}

arg_format() { # token
    esc EL0

    case "$format" in
	basename) printf %s "${1##*/}" ;;
	nldel) printf %s "${1%$nl}" ;;
	'') printf %s "$1" ;;
    esac
    esc SGR
    printf '\r'
}

status_line_top () {
    esc DECSC
    esc CUP 1
    case $USER in
        root) esc SGR 31 7 ;;
	*) [ -n "$urgent" ] && esc SGR 31 7 || esc SGR 36 7 ;;
    esac
    printf '%*s\r' "$COLUMNS"
    case $msg in
	'') printf %s "shmenu" ;;
	*) printf %s "$msg" ;;
    esac
    esc SGR
    esc DECRC
}

status_line_bottom () {
    esc DECSC
    esc CUP "$LINES"
    case $USER in
        root) esc SGR 31 7 ;;
	*) [ -n "$urgent" ] && esc SGR 93 7 || esc SGR 34 7
    esac
    printf '%*s\r%s ' "$COLUMNS" "" "($y/$1)"
    case $ltype in
	'') printf %s "Menu system written in POSIX shell" ;;
	*) printf %s "$ltype" ;;
    esac
    esc SGR
    esc DECRC
}


term_move_up() {

    local fraction=$1; shift 1

    case $fraction in
        0) move=1 ;; # fraction=0, scroll up
	*) move=$(((end - top) / (fraction * num) > 2 ? (end - top) / (fraction * num) : 2)) ;; # fraction>0, page up
    esac

    case $y in
	-*|0|1) return ;;
    esac
    case $((y - 1 - move)) in
	-*|0) move=$((y - 1)) ;;
    esac

    y=$((y - move)) pos=$(( num * y - num + top ))

    for i in $(seq $((y + 1)) $((y + move))); do
	arg_print "$((y + move - i + y + 1))" "$@"
	case "$y2" in
	    $top) [ $num -gt 1 ] && esc CUU $((num - 1)); esc IL "$num" ;;
	    *) esc CUU "$((num * 2 - 1))"; y2=$(( y2 > top ? y2 - num : top )) ;;
	esac
    done
    arg_print "$y" "$@"

    # Restore cursor to match y2
    [ $num -gt 1 ] && esc CUU "$((num - 1))"
    status_line_top
    status_line_bottom "$#"
}

term_move_down() {

    local fraction=$1; shift 1

    case $fraction in
        0) move=1 ;; # fraction=0, scroll down
	*) move=$(((end - top) / (fraction * num) > 2 ? (end - top) / (fraction * num) : 2)) ;; # fraction>0, page down
    esac

    case $(( y - $# + move )) in
	[1-9]*) move=$(($# - y)) ;;
    esac

    y=$(( y + move ))
    pos=$(( num * y - num + top ))
    y2=$(( y2 + num * move < fin - (num - 1) ? y2 + num * move : fin - (num - 1) ))


    for i in $(seq $((y - move)) $((y - 1))); do
	arg_print "$i" "$@"
	printf '\n'
    done
    arg_print "$y" "$@"

    [ $num -gt 1 ] && esc CUU "$((num - 1))"

    status_line_top
    status_line_bottom "$#"
}

prompt() {
    esc DECSC
    esc CUP "$LINES"
    printf %s "$1"
    esc DECTCEM h
    esc EL0

    case $2 in
        r)
	    stty -cread icanon echo 1>/dev/null 2>&1
	    read -r ans ||:
	    stty -icanon -echo
	    ;;
    esac

    esc DECRC
    esc DECTCEM l
    status_line_bottom "($y/$#) $PWD"
}

search() {
    local IFS="$2"
    local str="$3"
    local filter
    set -- $1
    for line do
	case $str in
	    *[[:upper:]]*) # contain uppercase, do case-sensitive filter
		case $line in
		    *$str*) filter="$filter$IFS$line" ;;
		esac
		;;
	    *) # o/w, do case-insensitive filter
		lower_line=$(printf '%s' "$line" | tr '[:upper:]' '[:lower:]')
		case $lower_line in
		    *$str*) filter="$filter$IFS$line" ;;
		esac
		;;
	esac
    done
    filt_out=${filter#*$IFS}
}

key() {
    while key=$(dd ibs=1 count=1 2>/dev/null); do
	case $key${esc:=0} in
	    "$ctrl_u"?|~5)
		term_move_up 4 "$@"
	    ;;

	    "$ctrl_f"?|~6)
		term_move_down 4 "$@"
	    ;;

	    k?|A2)
		term_move_up 0 "$@"
	    ;;

            j?|B2)
		term_move_down 0 "$@"
	    ;;

            g?|H2)
                case $y in
                    1) continue ;;
                esac

                y=1 y2=$top cur=$1
		redraw "$@"
            ;;

            G?|F2)
		y=$# pos=$(( num * y - num + top ))
		y2=$(( pos < fin - (num - 1) ? pos : fin - (num - 1) ))
		cur_assign "$y" "$@"
		redraw "$@"
            ;;

            l?|C2|"$esc") # ARROW RIGHT
		term_reset
		return 2
            ;;

            h?|D2|"$bs_char"?) # ARROW LEFT

		[ -n "$search_ind" ] || [ -n "$help_ind" ] &&
		    {
			unset search_ind help_ind
			IFS=$ifs
			set -- $text
			unset IFS
			hist=1
			old_reset "$@"
			redraw "$@"
		    }
            ;;

            /?)
                prompt / r
		search "$text" "$ifs" "$ans"
		local search_ind=1
		IFS=$ifs
		set -- $filt_out
		unset IFS
                case $# in
                    0)
			num=1
			set -- 'no result'
			;;
                esac

		old_num=$num old_y=$y old_y2=$y2 old_pos=$pos old_cur=$cur
		y=1 y2=$top cur=$1 ltype="Search mode" msg="Search by *$ans*"
                redraw "$@"
            ;;

            \??)
		local help_ind=1
		set -- 'k/↑ - up' \
		       'j/↓ - down' \
		       'l/→ - right' \
		       'h/← - left' \
		       'Ctrl-f/PageDown - PageDown' \
		       'Ctrl-u/PageUp - PageUp' \
		       'g/Home - go to top' \
		       'G/End - go to bottom' \
		       '/ - search' \
		       '? - show keybinds' \
		       'q - quit'

		old_num=$num old_y=$y old_y2=$y2 old_pos=$pos old_cur=$cur
                num=1 y=1 y2=$top cur=$1 ltype= msg=keybinds token='?'
                redraw "$@"
            ;;

            q?)
		term_reset
		exit 0
		;;
            "$esc_c"*) esc=1 ;;
                 '[1') esc=2 ;;
		   5?) esc=5 ;; # PageUp
		   6?) esc=6 ;; # PageDown
                    *) esc=0 ;;
	esac
    done
}

usage () {
cat << 	EOF
Usage:

shmenu [OPTIONS] ([ARGS])

  -h,			Show help options
  -n=[num]		Set numbers of line per entry
  -s=[IFS]		Set IFS
  -t=[text]		Set text to display
  -f=[format]		Set the format to print out text

format detail:
  nldel			delete last nl, equiv to "\${1%\$nl}"
  basename		only print basename, equiv to "\${1##*/}" ;;

  if unset or empty, then equiv to "\$1"

EOF
}

main() {

    trap 'term_reset' INT
    trap 'term_resize; term_setup; y=1 y2=$top; redraw "$@"' WINCH

    term_resize

    IFS=${ifs:=$nl}
    set -- $text
    unset IFS

    term_setup
    y=1 y2=$top cur=$1
    redraw "$@"

    key "$@"

}

nl='
'
tab='	'

# special key setting
esc_c=$(printf '\033')
bs_char=$(printf '\177')
ctrl_f=$(printf '\006')
ctrl_u=$(printf '\025')
tilda=$(printf '\176')

while getopts "n:s:t:f:uh" result; do
    case "${result}" in
        n) num=${OPTARG} ;;
        s) ifs=${OPTARG} ;;
        t) text=${OPTARG} ;;
        f) format=${OPTARG} ;;
	u) urgent=1 ;;
	h) usage && exit 0 ;;
    esac
done

# Accept pipe stdin
[ "$text" = '-' ] && text=$(cat -u -)

if [ -n "$num" ] && [ -n "$text" ]; then
    main "$@" <&2 >/dev/tty # why it works, I don't know.
    printf '%s' "$cur" >&1
else
    printf '%s' 'Need to use `-n` to specify numbers of line per entry, and use `-t` for text to display.'
    exit 0
fi
